server:
  port: 9019
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9012/eureka/